### ISSUE TITLE
Ideas for code design and repository structure

### ISSUE THREAD

**Issue by naliboff** [gdmate/gdmate#11]
First order and interrelated questions about GDMATE:

1. Should we use a functional or objected oriented programming style?
2. What should the directory structure look like?
3. How should files and topics be organized?

**Comment by naliboff** [comment]
Initial thoughts about each question:

1. A functional programming style will lower the barrier of entry for new contributors. We can also reorganize functions into various classes later on.

2. In the home folder of the repository (gdmate/), we should have the following sub-folders:
2.1 gdmate/ - main source code folder with various toolkits. Further sub-folders organized by category (see below).
2.2 examples/ - python (or Julia) scripts showing how to use the various toolkits
2.3 tests/ - tests for source code and examples
2.4 tutorials/ - jupyter notebooks providing background training, highlighting various examples, education modules, etc.

3. The source code (gdmate/gdmate/) should contain subfolders and files that are organized by common utilities. For example, examples of first-level subfolders could be utilities/, model_inputs/, model_analysis/, and education/. Subfolders within model_analysis/ could be visualization/, feature_extraction/, etc.

**Comment by dyvasey** [comment]
If possible, we may want to avoid using more than one subfolder within the source code, because it starts to make the imports for modules somewhat verbose: https://peps.python.org/pep-0423/#avoid-deep-nesting.

I notice, for example, that Burnman only has one level of subdirectory within the main burnman/burnman directory.

**Comment by naliboff** [comment]
> If possible, we may want to avoid using more than one subfolder within the source code, because it starts to make the imports for modules somewhat verbose

Good point. For now, should we just try to have only one set of subfolders within the source code folder? For example these could be:

- Utilities

**Comment by naliboff** [comment]
A slight permutation on the the directory structure above:

- `education`
- `visualization`
- `analysis`
- `utilities`

**Comment by dyvasey** [comment]
Following discussion with Rene and others at CIG meeting, seems like we should avoid overly generic subdirectories if possible. Structure suggested by John:

_I agree that getting a new repository structure in place is crucial._

_For now, I can think of the following directories:_
visualization
io
fault_analysis
rheology
code_coupling
education

**Comment by naliboff** [comment]
Updated ideas on how to structure the repository after looking through

**Comment by dyvasey** [comment]
Working on implementing this now in #21. A question though: do we need source code modules under `education`? Or is `education` a separate top-level directory with things like Jupyter Notebooks?

**Comment by dyvasey** [comment]
I'm going to mark this as closed for now, since we have an initial repository structure that we can revisit at a later time if needed.
